# Generated by Django 2.2.28 on 2022-07-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfume_name', models.CharField(max_length=255, verbose_name='Название аромата')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('gender', models.CharField(choices=[('Uncathegorized', 'Не определено'), ('Female', 'Для женщин'), ('Unisex', 'Унисекс'), ('Male', 'Для мужчин')], default='Uncathegorized', max_length=50, verbose_name='Пол')),
                ('perfume_group', models.CharField(choices=[('Uncathegorized', 'Не определено'), ('Amber', 'Восточные'), ('AmberFloral', 'Восточные цветочные'), ('AmberFougere', 'Восточные фужерные'), ('AmberSpicy', 'Восточные пряные'), ('AmberVanilla', 'Восточные гурманские'), ('AmberWoody', 'Восточные древесные'), ('AromaticAquatic', 'Фужерные водяные'), ('AromaticFougere', 'Фужерные'), ('AromaticFruity', 'Фужерные фруктовые'), ('AromaticGreen', 'Фужерные зеленые'), ('AromaticSpicy', 'Фужерные пряные'), ('Chypre', 'Шипровые'), ('ChypreFloral', 'Шипровые цветочные'), ('ChypreFruity', 'Шипровые фруктовые'), ('Citrus', 'Цитрусовые'), ('CitrusAromatic', 'Цитрусовые фужерные'), ('CitrusGourmand', 'Цитрусовые сладкие'), ('Floral', 'Цветочные'), ('FloralAldehyde', 'Цветочные альдегидные'), ('FloralAquatic', 'Цветочные водяные'), ('FloralFruity', 'Цветочные фруктовые'), ('FloralFruityGourmand', 'Цветочные фруктовые сладкие'), ('FloralGreen', 'Цветочные зеленые'), ('FloralWoodyMusk', 'Цветочные древесно-мускусные'), ('Leather', 'Кожаные'), ('Woody', 'Древесные'), ('WoodyAquatic', 'Древесные водяные'), ('WoodyAromatic', 'Древесные фужерные'), ('WoodyChypre', 'Древесные шипровые'), ('WoodyFloralMusk', 'Древесные цветочные мускусные'), ('WoodySpicy', 'Древесные пряные')], default='Uncathegorized', max_length=200, verbose_name='Парфюмерное семейство')),
                ('season', models.CharField(choices=[('Uncathegorized', 'Не определено'), ('AllSeasons', 'Все сезоны'), ('HotSeasons', 'Теплый-жаркий сезон'), ('ColdSeasons', 'Холодный сезон')], default='Uncathegorized', max_length=50, verbose_name='Сезонность')),
                ('usage', models.CharField(choices=[('Uncathegorized', 'Не определено'), ('AllpurposedUsage', 'Универсальное использование'), ('ForWork', 'Для повседневного ношения'), ('ToGoOut', 'Для выхода в свет')], default='Uncathegorized', max_length=100, verbose_name='Когда используется')),
                ('top_notes', models.CharField(blank=True, max_length=500, verbose_name='Верхние ноты')),
                ('middle_notes', models.CharField(blank=True, max_length=500, verbose_name='Средние ноты')),
                ('base_notes', models.CharField(blank=True, max_length=500, verbose_name='Ноты сердца')),
                ('image_url', models.URLField(default='/static/img/defaultimage.jpg', verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Парфюм',
                'ordering': ('pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='perfume',
            constraint=models.UniqueConstraint(fields=('perfume_name', 'brand'), name='unique_perfume'),
        ),
    ]
