# Generated by Django 2.2.28 on 2022-10-09 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Здесь можно ввести текст заметки', verbose_name='Заметка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата написания заметки')),
                ('perfume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='perfumes.Perfume', verbose_name='Парфюм')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ('created',),
            },
        ),
    ]
