# Generated by Django 2.2.28 on 2023-01-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='had_it',
            field=models.BooleanField(default=False, verbose_name='Был'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='have_it',
            field=models.BooleanField(default=False, verbose_name='Есть'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='test_it',
            field=models.BooleanField(default=False, verbose_name='Нужно попробовать'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='want_it',
            field=models.BooleanField(default=False, verbose_name='Хочу приобрести'),
        ),
    ]
