# Generated by Django 3.2.18 on 2023-05-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0003_presence_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='slug',
            field=models.SlugField(default='new-perfume', verbose_name='Название для ссылки'),
        ),
    ]
